### ISSUE TITLE
Automated Issue: Use Our `git-repo-sync` in Mirror CI.

### ISSUE THREAD

**Issue by TheHamsterBot** [offensive-vk/offensive-vk#27455]
## Please Fix this Workflow

```yaml
name: 🦅 Mirror Sync

on:
  schedule:
    - cron: '0 */2 * * *'
  push:
    branches: ['**']
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Ping Repos
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          target-url: ${{ secrets.TARGET_URL }}
          target-username: ${{ secrets.TARGET_USER }}
          target-token: ${{ secrets.TARGET_TOKEN }}

```
